"use client";
import {useEffect,useRef,useState} from 'react';import {useAdmin} from '../AdminContext';import {DEFAULT_SETTINGS} from '@/lib/settings';import type {SiteSettings} from '@/lib/types';import toast from 'react-hot-toast';import {Save,Upload,Loader2,Image as ImageIcon,ExternalLink} from 'lucide-react';
type UploadTarget=keyof Pick<SiteSettings,'logo_url'|'hero_image'|'hero_image_mobile'|'purpose_image_left'|'purpose_image_right'>;
const groups=[
  {t:'Brand',d:'Nome, announcement bar e identità principale.',f:[['brand_name','Brand name','input'],['announcement','Announcement bar','input'],['announcement_url','Announcement link','input'],['contact_email','Contact email','input']]},
  {t:'Hero',d:'Prima sezione della homepage.',f:[['hero_eyebrow','Hero eyebrow','input'],['hero_title','Hero title','input'],['hero_subtitle','Hero subtitle','textarea'],['hero_button_label','Primary button label','input'],['hero_button_url','Primary button URL','input'],['secondary_button_label','Secondary button label','input'],['secondary_button_url','Secondary button URL','input'],['hero_overlay_opacity','Hero overlay opacity 0 - 0.75','input']]},
  {t:'Best sellers',d:'Titolo e testo sopra ai prodotti in evidenza.',f:[['best_sellers_title','Section title','input'],['best_sellers_subtitle','Section subtitle','textarea']]},
  {t:'Made with purpose',d:'Testo centrale e due immagini stile editoriale.',f:[['purpose_eyebrow','Eyebrow','input'],['purpose_title','Title','input'],['purpose_text','Text','textarea'],['purpose_button_label','Button label','input'],['purpose_button_url','Button URL','input']]},
  {t:'Studio & care',d:'Testi istituzionali, spedizioni, resi e cura.',f:[['about_title','About title','input'],['about_text','About text','textarea'],['shipping_text','Shipping text','textarea'],['returns_text','Return policy','textarea'],['care_text','Care instructions','textarea']]},
  {t:'Social & newsletter',d:'Link social e footer.',f:[['instagram_url','Instagram URL','input'],['instagram_handle','Instagram handle','input'],['instagram_feed_mode','Instagram mode: manual oppure latest','input'],['instagram_access_token','Instagram access token opzionale per ultimi post','input'],['instagram_post_image_1','Instagram post image 1','input'],['instagram_post_url_1','Instagram post URL 1','input'],['instagram_post_image_2','Instagram post image 2','input'],['instagram_post_url_2','Instagram post URL 2','input'],['instagram_post_image_3','Instagram post image 3','input'],['instagram_post_url_3','Instagram post URL 3','input'],['instagram_post_image_4','Instagram post image 4','input'],['instagram_post_url_4','Instagram post URL 4','input'],['tiktok_url','TikTok URL','input'],['pinterest_url','Pinterest URL','input'],['newsletter_title','Newsletter title','input'],['newsletter_text','Newsletter text','textarea']]},
  {t:'Colors',d:'Personalizza colori principali del sito. Usa valori HEX.',f:[['announcement_bg_color','Announcement background','color'],['announcement_text_color','Announcement text','color'],['header_bg_color','Header background','color'],['page_bg_color','Page background','color'],['product_card_bg_color','Product card background','color'],['footer_bg_color','Footer background','color'],['footer_text_color','Footer text','color'],['button_bg_color','Button background','color'],['button_text_color','Button text','color'],['text_color','Main text','color'],['muted_text_color','Muted text','color']]}
] as const;
const imgs:{key:UploadTarget;label:string;ratio:string;hint:string}[]=[{key:'logo_url',label:'Logo',ratio:'aspect-[3/1]',hint:'PNG trasparente consigliato.'},{key:'hero_image',label:'Hero desktop',ratio:'aspect-[16/10]',hint:'Foto principale homepage.'},{key:'hero_image_mobile',label:'Hero mobile',ratio:'aspect-[4/5]',hint:'Opzionale verticale.'},{key:'purpose_image_left',label:'Purpose left',ratio:'aspect-[4/5]',hint:'Foto sinistra.'},{key:'purpose_image_right',label:'Purpose right',ratio:'aspect-[4/5]',hint:'Foto destra.'}];
export default function SettingsPage(){const{adminKey}=useAdmin();const[form,setForm]=useState<SiteSettings>(DEFAULT_SETTINGS);const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState<UploadTarget|null>(null);const[target,setTarget]=useState<UploadTarget>('hero_image');const fileRef=useRef<HTMLInputElement>(null);useEffect(()=>{fetch('/api/settings',{cache:'no-store'}).then(r=>r.json()).then(d=>setForm({...DEFAULT_SETTINGS,...d})).catch(()=>toast.error('Impossibile caricare le impostazioni'))},[]);function patch(key:keyof SiteSettings,value:string){setForm(p=>({...p,[key]:value}))}async function save(){setSaving(true);const r=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-key':adminKey},body:JSON.stringify(form)});setSaving(false);if(r.ok){setForm({...DEFAULT_SETTINGS,...await r.json()});localStorage.setItem('balisa-settings-updated',Date.now().toString());window.dispatchEvent(new Event('balisa-settings-updated'));toast.success('Sito aggiornato e pubblicato')}else toast.error((await r.json()).error||'Errore salvataggio')}async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(target);const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',headers:{'x-admin-key':adminKey},body:fd});const d=await r.json();setUploading(null);if(d.url){setForm(p=>({...p,[target]:d.url}));toast.success('Immagine caricata. Premi Salva per pubblicare.')}else toast.error(d.error||'Errore upload');if(fileRef.current)fileRef.current.value=''}function startUpload(t:UploadTarget){setTarget(t);setTimeout(()=>fileRef.current?.click(),0)}return <div><div className="mb-8 flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><h1 className="font-serif text-4xl">Website editor</h1><p className="text-white/40 mt-2 text-sm max-w-2xl">Modifica homepage, testi, immagini, logo e contenuti principali. Le anteprime si aggiornano subito; il sito cambia quando salvi.</p></div><div className="flex gap-3"><a href="/" target="_blank" className="border border-white/15 rounded-2xl px-5 py-3 text-xs uppercase tracking-[.16em] flex items-center gap-2 hover:bg-white/10"><ExternalLink size={15}/> Apri sito</a><button onClick={save} disabled={saving} className="bg-gold text-ink rounded-2xl px-5 py-3 text-xs uppercase tracking-[.16em] font-bold flex items-center gap-2 disabled:opacity-60">{saving?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>} Salva tutto</button></div></div><div className="grid xl:grid-cols-[1fr_420px] gap-6"><section className="grid gap-6">{groups.map(g=><div key={g.t} className="admin-panel p-5 lg:p-7"><div className="mb-5"><h2 className="font-serif text-2xl">{g.t}</h2><p className="text-white/35 text-sm mt-1">{g.d}</p></div><div className="grid gap-4">{g.f.map(([key,label,type])=><label key={key}><span className="admin-label">{label}</span>{type==='textarea'
  ? <textarea rows={4} className="admin-input" value={(form[key as keyof SiteSettings] as string)||''} onChange={e=>patch(key as keyof SiteSettings,e.target.value)}/>
  : type==='color'
    ? <div className="flex gap-3"><input type="color" className="admin-input admin-color-input w-20" value={(form[key as keyof SiteSettings] as string)||'#ffffff'} onChange={e=>patch(key as keyof SiteSettings,e.target.value)}/><input className="admin-input" value={(form[key as keyof SiteSettings] as string)||''} onChange={e=>patch(key as keyof SiteSettings,e.target.value)} placeholder="#ffffff"/></div>
    : <input className="admin-input" value={(form[key as keyof SiteSettings] as string)||''} onChange={e=>patch(key as keyof SiteSettings,e.target.value)}/>
}</label>)}</div></div>)}</section><aside className="grid gap-5 h-fit xl:sticky xl:top-8"><input ref={fileRef} type="file" accept="image/*" hidden onChange={upload}/>{imgs.map(card=><div key={card.key} className="admin-panel p-5"><div className="flex items-center justify-between gap-4 mb-3"><div><h3 className="font-serif text-xl">{card.label}</h3><p className="text-xs text-white/35 mt-1">{card.hint}</p></div><button onClick={()=>startUpload(card.key)} className="border border-white/15 rounded-xl px-3 py-2 text-xs uppercase tracking-[.14em] flex items-center gap-2 hover:bg-white/10">{uploading===card.key?<Loader2 className="animate-spin" size={14}/>:<Upload size={14}/>} Upload</button></div><div className={`${card.ratio} rounded-2xl bg-white/5 overflow-hidden border border-white/10`}>{form[card.key]?<img src={form[card.key] as string} className="w-full h-full object-cover" alt={card.label}/>:<div className="h-full grid place-items-center text-white/25"><ImageIcon size={24}/></div>}</div><input className="admin-input mt-3 text-xs" value={(form[card.key] as string)||''} onChange={e=>patch(card.key,e.target.value)} placeholder="Image URL"/></div>)}</aside></div></div>}
