"use client";
import { useEffect, useState, useRef } from 'react';
import { useAdmin } from '../AdminContext';
import { DEFAULT_SETTINGS } from '@/lib/settings';
import toast from 'react-hot-toast';
import { Save, Upload, Loader2 } from 'lucide-react';
const fields = [['hero_eyebrow','Hero eyebrow'],['hero_title','Hero title'],['hero_subtitle','Hero subtitle'],['announcement','Top announcement'],['instagram_url','Instagram URL'],['instagram_handle','Instagram handle'],['contact_email','Contact email'],['about_title','About title'],['about_text','About text'],['shipping_text','Shipping text'],['returns_text','Return policy']];
export default function SettingsPage(){const {adminKey}=useAdmin(); const [form,setForm]=useState<any>(DEFAULT_SETTINGS); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const fileRef=useRef<HTMLInputElement>(null); useEffect(()=>{fetch('/api/settings').then(r=>r.json()).then(d=>setForm({...DEFAULT_SETTINGS,...d}))},[]); async function save(){setSaving(true); const r=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-key':adminKey},body:JSON.stringify(form)}); setSaving(false); r.ok?toast.success('Website content updated'):toast.error((await r.json()).error||'Error');} async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]; if(!file)return; setUploading(true); const fd=new FormData(); fd.append('file',file); const r=await fetch('/api/upload',{method:'POST',headers:{'x-admin-key':adminKey},body:fd}); const d=await r.json(); setUploading(false); if(d.url){setForm((p:any)=>({...p,hero_image:d.url})); toast.success('Hero image uploaded. Click Save to publish.')}else toast.error(d.error||'Upload error'); if(fileRef.current)fileRef.current.value='';}
return <div><div className="mb-8"><h1 className="font-serif text-4xl">Website editor</h1><p className="text-white/40 mt-2 text-sm">Edit homepage copy, hero image, contact details, shipping and returns without code.</p></div><div className="grid lg:grid-cols-[1fr_360px] gap-6"><section className="admin-panel p-5 lg:p-7 grid gap-5">{fields.map(([key,label])=><label key={key}><span className="admin-label">{label}</span>{key.includes('text')||key.includes('subtitle')||key==='about_text'?<textarea rows={4} className="admin-input" value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input className="admin-input" value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<button onClick={save} disabled={saving} className="bg-gold text-ink rounded-2xl px-5 py-4 text-xs uppercase tracking-[.18em] font-bold flex justify-center gap-2 disabled:opacity-60">{saving?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>} Save and publish</button></section><aside className="admin-panel p-5 lg:p-7 h-fit"><h2 className="font-serif text-2xl mb-4">Hero image</h2><div className="aspect-[4/5] rounded-3xl bg-white/5 overflow-hidden border border-white/10 mb-4">{form.hero_image?<img src={form.hero_image} className="w-full h-full object-cover" alt="Hero preview"/>:<div className="h-full grid place-items-center text-white/20">No image</div>}</div><input ref={fileRef} type="file" accept="image/*" hidden onChange={upload}/><button onClick={()=>fileRef.current?.click()} className="w-full border border-white/15 rounded-2xl py-3 text-xs uppercase tracking-[.16em] flex justify-center gap-2 hover:bg-white/10">{uploading?<Loader2 className="animate-spin" size={15}/>:<Upload size={15}/>} Upload image</button><p className="text-xs leading-6 text-white/35 mt-4">Preview updates immediately. Saving publishes the image and text to the storefront.</p></aside></div></div>}
