import { supabase } from '@/lib/supabase';
import { Product } from '@/lib/types';
import ProductCard from '@/components/ProductCard';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Sparkles, Globe2, Scissors } from 'lucide-react';
import { getSiteSettings } from '@/lib/settings';

export const dynamic = 'force-dynamic';
async function getFeatured(): Promise<Product[]> { const { data } = await supabase.from('products').select('*').eq('featured',true).order('created_at',{ascending:false}).limit(4); return (data as Product[])||[]; }
async function getLatest(): Promise<Product[]> { const { data } = await supabase.from('products').select('*').order('created_at',{ascending:false}).limit(3); return (data as Product[])||[]; }
export default async function HomePage(){
  const [settings, featured, latest] = await Promise.all([getSiteSettings(), getFeatured(), getLatest()]);
  const hero = settings.hero_image || featured[0]?.images?.[0] || latest[0]?.images?.[0];
  return <main className="pt-28">
    <section className="max-w-7xl mx-auto px-5 lg:px-10 py-10 lg:py-20 grid lg:grid-cols-[1.05fr_.95fr] gap-10 items-center">
      <div className="fade-up"><p className="kicker mb-5">{settings.hero_eyebrow}</p><h1 className="font-serif text-[clamp(3.3rem,8vw,7.7rem)] leading-[.9] tracking-[-.04em] max-w-4xl">{settings.hero_title}</h1><p className="mt-7 text-lg lg:text-xl text-ink/60 leading-8 max-w-xl">{settings.hero_subtitle}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/shop" className="btn-dark">Shop collection <ArrowRight size={16}/></Link><a href={settings.instagram_url} target="_blank" className="btn-light">Instagram</a></div></div>
      <div className="relative"><div className="absolute -inset-5 bg-rose/40 rounded-[48px] rotate-3"/><div className="relative aspect-[4/5] rounded-[42px] bg-stone overflow-hidden shadow-soft">{hero?<Image src={hero} alt="OKKA handmade bag" fill priority className="object-cover"/>:<div className="h-full grid place-items-center logo-word text-7xl text-black/10">OKKA</div>}</div></div>
    </section>
    <section className="border-y border-black/10 bg-white"><div className="max-w-7xl mx-auto px-5 lg:px-10 py-6 grid md:grid-cols-3 gap-5"><div className="flex gap-3"><Scissors className="text-gold"/><p className="text-sm uppercase tracking-[.14em]">Handmade finish</p></div><div className="flex gap-3"><Sparkles className="text-gold"/><p className="text-sm uppercase tracking-[.14em]">Limited pieces</p></div><div className="flex gap-3"><Globe2 className="text-gold"/><p className="text-sm uppercase tracking-[.14em]">International shipping</p></div></div></section>
    <section className="max-w-7xl mx-auto px-5 lg:px-10 py-20"><div className="flex justify-between items-end mb-10"><div><p className="kicker mb-3">Your favourites</p><h2 className="font-serif text-5xl tracking-[-.03em]">Signature pieces</h2></div><Link href="/shop" className="hidden md:flex items-center gap-2 text-xs uppercase tracking-[.18em]">View all <ArrowRight size={14}/></Link></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-5 lg:gap-7">{(featured.length?featured:latest).map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></section>
    <section id="about" className="bg-stone py-20"><div className="max-w-7xl mx-auto px-5 lg:px-10 grid lg:grid-cols-2 gap-12 items-center"><div><p className="kicker mb-4">About OKKA</p><h2 className="font-serif text-5xl lg:text-7xl leading-[.95] tracking-[-.04em]">{settings.about_title}</h2></div><div><p className="text-xl text-ink/65 leading-9">{settings.about_text}</p><div className="mt-10 grid grid-cols-3 gap-4"><div><b className="font-serif text-4xl">01</b><p className="text-xs uppercase tracking-[.16em] text-ink/45 mt-2">Small batch</p></div><div><b className="font-serif text-4xl">100%</b><p className="text-xs uppercase tracking-[.16em] text-ink/45 mt-2">Handmade</p></div><div><b className="font-serif text-4xl">∞</b><p className="text-xs uppercase tracking-[.16em] text-ink/45 mt-2">Custom spirit</p></div></div></div></div></section>
    <section id="faq" className="max-w-5xl mx-auto px-5 lg:px-10 py-20"><p className="kicker mb-4 text-center">Customer care</p><h2 className="font-serif text-5xl text-center mb-10">More information</h2><div className="grid md:grid-cols-2 gap-4"><details className="bg-white rounded-3xl border border-black/10 p-6"><summary className="cursor-pointer font-semibold">Shipping</summary><p className="mt-4 text-ink/60 leading-7">{settings.shipping_text}</p></details><details className="bg-white rounded-3xl border border-black/10 p-6"><summary className="cursor-pointer font-semibold">Return policy</summary><p className="mt-4 text-ink/60 leading-7">{settings.returns_text}</p></details><details className="bg-white rounded-3xl border border-black/10 p-6"><summary className="cursor-pointer font-semibold">Bag care</summary><p className="mt-4 text-ink/60 leading-7">Spot clean gently with cold water. Store flat or stuffed to preserve shape.</p></details><details className="bg-white rounded-3xl border border-black/10 p-6"><summary className="cursor-pointer font-semibold">Contact</summary><p className="mt-4 text-ink/60 leading-7">Email: {settings.contact_email}<br/>Instagram: {settings.instagram_handle}</p></details></div></section>
  </main>
}
