import { supabase } from '@/lib/supabase';
import { Product } from '@/lib/types';
import { formatPrice } from '@/lib/stripe';
import { notFound } from 'next/navigation';
import ProductActions from './ProductActions';
import Image from 'next/image';
import Link from 'next/link';
import type { Metadata } from 'next';
export const dynamic='force-dynamic';
async function getProduct(slug:string):Promise<Product|null>{const {data}=await supabase.from('products').select('*').eq('slug',slug).single(); return data as Product||null;}
export async function generateMetadata({params}:{params:{slug:string}}):Promise<Metadata>{const p=await getProduct(params.slug); if(!p)return{}; return{title:`${p.name} | OKKA`,description:p.description,openGraph:{title:`${p.name} | OKKA`,description:p.description,images:p.images?.[0]?[p.images[0]]:[]}}}
export default async function ProductPage({params}:{params:{slug:string}}){const product=await getProduct(params.slug); if(!product)notFound(); return <main className="pt-32"><div className="max-w-7xl mx-auto px-5 lg:px-10 py-4"><nav className="text-[11px] uppercase tracking-[.18em] text-ink/40"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/shop">Shop</Link><span className="mx-2">/</span><span>{product.name}</span></nav></div><section className="max-w-7xl mx-auto px-5 lg:px-10 py-8 grid lg:grid-cols-2 gap-10 lg:gap-16 items-start"><div className="grid gap-4">{product.images?.length?product.images.map((img,i)=><div key={img} className="relative aspect-square bg-stone rounded-[34px] overflow-hidden border border-black/5"><Image src={img} alt={`${product.name} image ${i+1}`} fill priority={i===0} className="object-cover"/></div>):<div className="aspect-square bg-stone rounded-[34px] grid place-items-center logo-word text-7xl text-black/10">OKKA</div>}</div><aside className="lg:sticky lg:top-32"><p className="kicker mb-3">OKKA · {product.category}</p><h1 className="font-serif text-5xl lg:text-7xl leading-[.95] tracking-[-.04em]">{product.name}</h1><p className="mt-5 text-2xl font-semibold">{formatPrice(product.price)}</p>{product.compare_at_price&&<p className="line-through text-ink/35 mt-1">{formatPrice(product.compare_at_price)}</p>}<p className="mt-8 text-lg leading-8 text-ink/62">{product.description}</p><div className="my-8 rounded-3xl bg-stone p-6 grid gap-4"><div className="flex justify-between gap-6"><span className="text-xs uppercase tracking-[.18em] text-ink/40">Colours</span><span className="text-sm text-right">{product.colors?.join(', ')||'As shown'}</span></div><div className="flex justify-between"><span className="text-xs uppercase tracking-[.18em] text-ink/40">Availability</span><span className="text-sm">{product.stock>0?`${product.stock} in stock`:'Sold out'}</span></div><div className="flex justify-between"><span className="text-xs uppercase tracking-[.18em] text-ink/40">Material</span><span className="text-sm text-right">{product.material||'Hand-crocheted yarn'}</span></div>{product.dimensions&&<div className="flex justify-between"><span className="text-xs uppercase tracking-[.18em] text-ink/40">Size</span><span className="text-sm text-right">{product.dimensions}</span></div>}</div><ProductActions product={product}/><div className="mt-8 grid grid-cols-3 gap-3 text-center text-[10px] uppercase tracking-[.14em] text-ink/45"><div className="rounded-2xl border border-black/10 p-4">Handmade</div><div className="rounded-2xl border border-black/10 p-4">Secure checkout</div><div className="rounded-2xl border border-black/10 p-4">Worldwide shipping</div></div></aside></section></main>}
